# Generated by Django 5.2 on 2025-04-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('square_meter', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
