# Generated by Django 5.2 on 2025-05-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_productdetail_location_product_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='price',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='bedrooms_max',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='bedrooms_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='price_max',
            field=models.DecimalField(decimal_places=2, default=9999999, max_digits=15),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='price_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
