# Generated by Django 5.2 on 2025-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_productdetail_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='square_meter',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='square_meter_max',
            field=models.CharField(default=1000, max_length=20),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='square_meter_min',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='bedrooms_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='bedrooms_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_min',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
