# Generated by Django 5.2 on 2025-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_productdetail_square_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='square_meter_max',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='square_meter_min',
            field=models.CharField(max_length=20),
        ),
    ]
