# Generated by Django 5.2 on 2025-05-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_productdetail_square_meter_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/apartament_details/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartament_details', to='website.productdetail')),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.productapartament'),
        ),
    ]
