# Generated by Django 5.2 on 2025-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_productapartament_alter_productimage_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productapartament',
            name='image',
        ),
    ]
