# Generated by Django 5.2 on 2025-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_productapartament_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productapartament',
            name='is_primary',
        ),
    ]
