# Generated by Django 5.2 on 2025-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_productapartament_bedrooms_productapartament_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapartament',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.productdetail'),
        ),
    ]
