# Generated by Django 5.2 on 2025-05-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_productapartament_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_detail',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_apartament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.productapartament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='uploads/product_apartaments/'),
        ),
    ]
