# Generated by Django 5.2 on 2025-06-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_productimage_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='price_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='price_min',
            field=models.IntegerField(default=0),
        ),
    ]
